### PR TITLE
added file I/O utils and some basic IO functions from brainrender

### PR DESCRIPTION
**Pull request by FedeClaudi**
Just add some generally useful functions

### CODE REVIEW

**Comment by vigji** [comment]
This is useful for creating the packages!

I am wondering whether we should have all the code for that in a separate private repo. But I think there's always time to refactor that out once things start getting more structured.

**Comment by FedeClaudi** [comment]
Most of this stuff comes from here: https://github.com/FedeClaudi/fcutils/blob/master/fcutils/file_io/io.py

I'd be happy to have a general utils repo though

**Comment by adamltyson** [comment]
Yeah, I think a proper conversation is needed at some point with regards to overall project structure.
There is cellfinder, amap, imlib, brainio, brainrender, morphapi and brainglobe, spread across 3 organisations. Maybe a separate discussion about github orgs, repos, and associated responsibilities would be good?

**Comment by FedeClaudi** [comment]
It would be great!

**Comment by adamltyson** [comment]
Any reason not to merge this?

**Pull request closed without merging**
